на проверку
Salimov-dev/fast_company_2 pull request #7
Opened 2022-11-18 15:22 UTC by Salimov-dev

2022-11-19 03:34 UTC, AndreiSachuk requested changes

2022-11-19 03:34 UTC, AndreiSachuk commented on src/components/usersList.jsx
> +          <Bookmarks items={props.items} item={item} bookmark={item.bookmark} id={item._id} setItems={props.setItems} />
Bookmarks    а чего во множественном числе?)

2022-11-19 03:34 UTC, AndreiSachuk commented on src/components/usersList.jsx
> +          <Qualities qualities={item.qualities} />
у тебя тут должен быть компонент Quality
 и ты мапом должен рендерить уникальный квалити один из этого компонента

2022-11-19 03:34 UTC, AndreiSachuk commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
мне очень не нравится, что этот метод находится здесь, а не там, где у тебя стэйт юзеров
зачем глубоко передать сэтстэйт, если ты можешь положить метод управления букмарками туда, где лежит твой стжэйт

2022-11-19 03:34 UTC, AndreiSachuk commented on src/components/bookmark.jsx
> +    newBookmark[elementIndex].bookmark === false
newBookmark[elementIndex].bookmark === false - это тоже, что и написать !newBookmark[elementIndex].bookmark

2022-11-19 16:59 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
![image](https://user-images.githubusercontent.com/108460956/202862588-23cbdff6-28ab-405f-97f3-10de3b3f419d.png)
![image](https://user-images.githubusercontent.com/108460956/202862602-541e2046-022b-41d9-a833-becf2f484621.png)

2022-11-19 17:00 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
тут я не понимаю, как из App.js передают в users.jsx
и что за объект ...rest? откуда взялся?

2022-11-19 17:01 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
![image](https://user-images.githubusercontent.com/108460956/202862672-1e021d82-84c3-4e5d-a364-22e2b06dbd86.png)
этот момент я тоже не понимаю, каким образом передаётся это

2022-11-19 17:03 UTC, Salimov-dev commented on src/components/usersList.jsx
> +          <Bookmarks items={props.items} item={item} bookmark={item.bookmark} id={item._id} setItems={props.setItems} />
поправил

2022-11-19 17:03 UTC, Salimov-dev commented on src/components/usersList.jsx
> +          <Qualities qualities={item.qualities} />
поправил

2022-11-19 17:03 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +    newBookmark[elementIndex].bookmark === false
поправил

2022-11-19 17:04 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
![image](https://user-images.githubusercontent.com/108460956/202862819-20532127-2e34-4fc1-98ed-92098b9b3bc8.png)
мне не понятно, как к этому пришло и не особо понимаю, как props в этом случае перестали использоваться

2022-11-19 17:05 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
в общем, согласен, что вынести удобнее туда, где юзстейт, но реализовать я этого не могу.
можешь помочь?

2022-11-20 02:44 UTC, AndreiSachuk commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
Таааакс))
Тут нам надо вспомнить, что такое spread/rest параметры и деструктуризация)
https://learn.javascript.ru/es-function

2022-11-20 08:31 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
Спасибо за наводочку, разберусь)

2022-11-20 19:36 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
закончил)
плюс-минус понятно стало с реструктуризацией, но повторить с нуля подобное, сейчас, я вряд-ли смогу без примеров)

2022-11-20 19:37 UTC, Salimov-dev commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
![image](https://user-images.githubusercontent.com/108460956/202922308-d595a14a-9ace-4a92-9581-db964e7981c3.png)
единственный не понятный для меня момент, это для чего кнопке button передается {...rest} - тут мог бы в паре слов пояснить, пожалуйста?)

2022-11-21 13:14 UTC, AndreiSachuk commented on src/components/bookmark.jsx
> +  const handleAddToBookmarks = (id, bookmark) => {
onClick

2022-11-21 15:39 UTC, merged